# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-12 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='working',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectmodule',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectmodule',
            name='important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectmodule',
            name='working',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='important',
            field=models.BooleanField(default=False),
        ),
    ]
