# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-12 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0002_auto_20181212_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectmodule',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
