# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-12 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0003_auto_20181212_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='projectmodule',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
